import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Blend",
    description: "Discover the true essence of coffee with our Roots Coffee Blend. This premium blend is carefully crafted from the finest coffee beans, sourced from the best plantations around the world. With its rich aroma and bold flavor, it offers a truly satisfying coffee experience. Start your day on the right note with Roots Coffee Blend.",
    image:
      "https://images.unsplash.com/photo-1656038005237-8a2ba5f6f0c9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=386&q=80",
    price: "767",
    discounted_price: "269",
    category_name: "Coffee Shop",
    category: "IND",
    availability: true,
    delivery_time: "6",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Roastery",
    description: "Experience the art of coffee roasting with Roots Coffee Roastery. Our expert roasters carefully select the finest coffee beans and roast them to perfection, unlocking their unique flavors and aromas. Each batch is a testament to our dedication to quality and craftsmanship. Indulge in the rich and complex flavors of Roots Coffee Roastery.",
    image:
      "https://images.unsplash.com/photo-1623659228341-21bc94462e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
    price: "599",
    discounted_price: "239",
    category_name: "Coffee Shop",
    category: "LKA",
    availability: true,
    delivery_time: "8",
    rating: "3.5",
  },
  {
    _id: uuid(),
    title: "Single Origin",
    description: "Experience the unique flavors of different coffee regions with Roots Coffee Single Origin. Each batch is carefully sourced from a specific coffee-growing region, allowing you to explore the diverse tastes that nature has to offer. From the earthy notes of South America to the vibrant flavors of Africa, let your taste buds embark on a journey with Roots Coffee Single Origin.",
    image:
      "https://images.unsplash.com/photo-1607681034540-2c46cc71896d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
    price: "999",
    discounted_price: "399",
    category_name: "Coffee Shop",
    category: "IND",
    availability: false,
    delivery_time: "7",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Signature Blend",
    description: "Introducing our finest creation, Roots Coffee Signature Blend. Meticulously crafted from a selection of premium coffee beans, this blend offers a harmonious balance of flavors and a smooth",
    image:
      "https://images.unsplash.com/photo-1509785307050-d4066910ec1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=728&q=80",
    price: "1099",
    discounted_price: "439",
    category_name: "Coffee Shop",
    category: "IND",
    availability: true,
    delivery_time: "2",
    rating: "2.0",
  },
  {
    _id: uuid(),
    title: "Decaf",
    description: "Enjoy the rich and robust flavors of coffee without the caffeine with Roots Coffee Decaf. Sourced from the highest quality beans, this decaffeinated blend undergoes a careful process that removes caffeine while preserving the exquisite taste. Whether you're seeking a late-night indulgence or a caffeine-free option, Roots Coffee Decaf delivers the perfect cup of coffee any time of the day.",
    image: "https://images.unsplash.com/photo-1516646227334-6102731f3c25?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
    price: "2299",
    discounted_price: "1379",
    category_name: "Coffee Shop",
    category: "LKA",
    availability: true,
    delivery_time: "5",
    rating: "1.0",
  },
  {
    _id: uuid(),
    title: "Accessories Set",
    description: "Elevate your coffee experience with the Roots Coffee Accessories Set. This curated collection includes everything you need to enjoy the perfect cup of coffee. From a stylish coffee grinder to a precision pour-over kettle and a selection of premium coffee beans, each item in this set is designed to enhance your brewing process and bring out the full flavors of Roots Coffee. Indulge in the art of coffee preparation with the Roots Coffee Accessories Set.",
    image:
      "https://images.unsplash.com/photo-1628236876894-dbde8ff5a944?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=442&q=80",
    price: "1439",
    discounted_price: "2399",
    category_name: "Coffee Shop",
    category: "ECU",
    availability: true,
    delivery_time: "4",
    rating: "4.7",
  },

  {
    _id: uuid(),
    title: "Single-Origin Ethiopia",
    description: "Experience the distinct flavors of Ethiopia with Roots Coffee Single-Origin Ethiopia. Sourced from the birthplace of coffee, this premium single-origin blend showcases the unique characteristics of Ethiopian beans. With a medium roast profile, it offers a harmonious balance of fruity notes, floral aromas, and a hint of chocolate. Indulge in the rich cultural heritage of Ethiopian coffee and savor the exquisite flavors that this origin has to offer.",
    image: "https://images.unsplash.com/photo-1447753072467-2f56032d1d48?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    price: "6499",
    discounted_price: "1999",
    category_name: "Coffee Shop",
    category: "IND",
    availability: true,
    delivery_time: "10",
    rating: "5.0",
  },
    {
    _id: uuid(),
    title: "Exquisite Tea Collection",
    description: "Indulge in the flavors of our Exquisite Tea Collection. Experience a delightful blend of hand-picked tea leaves and aromatic spices that will awaken your senses. From refreshing green teas to rich black teas, our collection offers a variety of flavors to suit every palate. Savor the perfect cup of tea and elevate your tea-drinking experience with our premium selection. Discover the art of tea with our Exquisite Tea Collection.",
      image:
        "https://images.unsplash.com/photo-1628153792464-21bffac488d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=580&q=80",
    price: "1199",
    discounted_price: "371",
    category_name: "Tea Shop",
    category: "LKA",
    availability: true,
    delivery_time: "7",
    rating: "4.1",
  },
  {
    _id: uuid(),
    title: "Classic Assam Black Tea",
description: "Savor the rich and robust flavor of our Classic Assam Black Tea. Grown in the fertile valleys of Assam, India, this tea offers a bold and full-bodied taste that tea enthusiasts will appreciate. With its deep amber color and malty undertones, it provides a satisfying and invigorating experience with every sip. Whether enjoyed hot or iced, our Classic Assam Black Tea is perfect for starting your day or enjoying a relaxing afternoon break. Discover the timeless charm of this renowned tea and elevate your tea-drinking experience.",
    image:
      "https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1587&q=80",
    price: "4199",
    discounted_price: "545",
    category_name: "Tea Shop",
    category: "ESP",
    availability: true,
    delivery_time: "6",
    rating: "1.5",
  },
  {
    _id: uuid(),
    title: "Gourmet Tea Delights",
description: "Indulge in the exquisite flavors of Gourmet Tea Delights. Our carefully curated collection of premium tea leaves and infusions offers a sensory journey like no other. From delicate floral notes to robust and earthy blends, each sip transports you to a world of refined taste and relaxation. Whether you prefer the boldness of black tea, the tranquility of green tea, or the soothing embrace of herbal infusions, Gourmet Tea Delights has a blend to suit every palate. Elevate your tea-drinking experience and savor the art of tea with Gourmet Tea Delights.",
image:
      "https://images.unsplash.com/photo-1433891248364-3ce993ff0e92?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
    price: "2396",
    discounted_price: "551",
    category_name: "Tea Shop",
    category: "IND",
    availability: true,
    delivery_time: "3",
    rating: "3.7",
  },
  {
    _id: uuid(),
    title: "Exotic Tea Delights",
description: "Embark on a journey of exquisite flavors with our Exotic Tea Delights collection. From the lush green tea gardens of Asia to the vibrant spice markets of the Middle East, we have curated a selection of the finest tea leaves and spices. Indulge in the captivating aroma and taste of our unique blends, meticulously crafted to transport you to distant lands with every sip. Elevate your tea-drinking experience with the richness and complexity of our Exotic Tea Delights. Discover a world of sensory delights in every cup.",
image:
      "https://images.unsplash.com/photo-1543060895-03f57478a710?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=389&q=80",
    price: "5555",
    discounted_price: "1388",
    category_name: "Tea Shop",
    category: "IND",
    availability: true,
    delivery_time: "6",
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "Spice Infusion",
    description: "Experience the bold and aromatic flavors of our Spice Infusion collection. Each blend is carefully crafted with a selection of premium spices sourced from around the world. From the warmth of cinnamon to the zing of ginger, these spices come together to create a symphony of taste in every sip. Indulge in the rich and diverse flavors of our Spice Infusion collection and elevate your tea-drinking experience. Discover a world of spice-infused delights with us.",
    image:
      "https://images.unsplash.com/photo-1607672632458-9eb56696346b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=957&q=80",
    price: "5999",
    discounted_price: "1999",
    category_name: "Tea Shop",
    category: "ESP",
    availability: true,
    delivery_time: "5",
    rating: "4.8",
  },
  {
    _id: uuid(),
    title: "Harmony Blend",
description: "Discover the perfect harmony of flavors with our exquisite blend of tea leaves. Carefully selected from the finest tea gardens, our Harmony Blend offers a balanced and aromatic experience for tea enthusiasts. Delight in the rich undertones of black tea, complemented by the subtle hints of floral and herbal infusions. Whether enjoyed hot or iced, this blend is a sensory journey that soothes the soul and invigorates the senses. Embrace the harmonious union of flavors and elevate your tea-drinking moments with Harmony Blend.",
    image:
      "https://images.unsplash.com/photo-1516715043227-1cdf27bcd09a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
    price: "2399",
    discounted_price: "1999",
    category_name: "Tea Shop",
    category: "LKA",
    availability: true,
    delivery_time: "8",
    rating: "4.5",
  },
    {
    _id: uuid(),
    title: "Exotic Spice Medley",
description: "Indulge in the tantalizing flavors of our Exotic Spice Medley. This carefully curated blend of aromatic spices from around the world will transport your taste buds to distant lands. Experience the warmth of cinnamon, the zing of ginger, the earthiness of cumin, and the subtle heat of chili. Perfect for enhancing the flavors of your favorite dishes, this spice medley adds a touch of culinary magic to every meal. Elevate your cooking to new heights with our Exotic Spice Medley and embark on a flavorful adventure.",
    image:
      "https://images.unsplash.com/photo-1504387828636-abeb50778c0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80",
    price: "300",
    discounted_price: "150",
    category_name: "Tea Shop",
    category: "ESP",
    availability: true,
    delivery_time: "5",
    rating: "3.1",
  },
  {
    _id: uuid(),
   title: "Exquisite Green Tea",
description: "Indulge in the refreshing and rejuvenating flavor of our Exquisite Green Tea. Sourced from the finest tea gardens, this premium green tea offers a delicate and smooth taste that is both calming and invigorating. With its vibrant green color and subtle floral notes, it provides a soothing and aromatic experience with every sip. Packed with antioxidants and known for its numerous health benefits, our Exquisite Green Tea is a perfect choice for tea enthusiasts seeking a harmonious blend of taste and wellness. Embrace the natural goodness of this exquisite tea and elevate your tea-drinking ritual.",
    image:
      "https://images.unsplash.com/photo-1585849835117-1446a1514ea6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
    price: "1999",
    discounted_price: "519",
    category_name: "Tea Shop",
    category: "ECU",
    availability: true,
    delivery_time: "8",
    rating: "2.5",
  },
  {
    _id: uuid(),
   title: "Earl Grey Tea",
description: "Experience the bold and distinctive flavor of our Earl Grey Tea. This classic tea blend combines high-quality black tea leaves with the essence of bergamot, a citrus fruit, to create a unique and aromatic infusion. With its rich and robust taste, Earl Grey Tea offers a perfect balance of floral and citrus notes, making it a beloved choice for tea lovers worldwide. Whether enjoyed hot or iced, this timeless tea is sure to awaken your senses and provide a moment of pure indulgence. Elevate your tea collection with our exquisite Earl Grey Tea and savor the timeless elegance it brings to every cup.",
    image:
      "https://images.unsplash.com/photo-1567922045116-2a00fae2ed03?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
    price: "1999",
    discounted_price: "799",
    category_name: "Tea Shop",
    category: "IND",
    availability: true,
    delivery_time: "3",
    rating: "4.5",
  },
  {
_id: uuid(),
title: "Sweet Delights",
description: "Experience a delectable array of sweet treats",
image:
"https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
price: "4999",
discounted_price: "699",
category_name: "Candy Shop",
category: "ESP",
availability: true,
delivery_time: "5",
rating: "4.3",
},
{
_id: uuid(),
title: "Choco Bliss",
description: "Indulge in the heavenly taste of Choco Bliss",
image:
"https://images.unsplash.com/photo-1517683551739-7f3f08efba84?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
price: "499",
discounted_price: "399",
category_name: "Candy Shop",
category: "ESP",
availability: true,
delivery_time: "5",
rating: "4.1",
},
{
_id: uuid(),
title: "Gummy Paradise",
description: "Step into a world of fruity delight with our Gummy Paradise",
image:
"https://images.unsplash.com/photo-1481391319762-47dff72954d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
price: "5999",
discounted_price: "1999",
category_name: "Candy Shop",
category: "ESP",
availability: true,
delivery_time: "5",
rating: "4.8",
},
{
_id: uuid(),
title: "Sugar Rush",
description:
"Experience the thrill of a sugar rush with our Sugar Rush collection",
image:
"https://images.unsplash.com/photo-1563262924-641a8b3d397f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
price: "1599",
discounted_price: "639",
category_name: "Candy Shop",
category: "ESP",
availability: true,
delivery_time: "5",
rating: "4.2",
},
{
_id: uuid(),
title: "Sweet Sensation",
  description: "Delight your senses with our Sweet Sensation collection",
  image:
      "https://images.unsplash.com/photo-1600359756098-8bc52195bbf4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=688&q=80",
    price: "1499",
    discounted_price: "899",
    category_name: "Candy Shop",
    category: "ESP",
    availability: true,
    delivery_time: "5",
    rating: "2.5",
  },
  {
    _id: uuid(),
     title: "Candyland Delights",
    description: "Embark on a sweet journey through Candyland Delights",
    image:
      "https://plus.unsplash.com/premium_photo-1663051126021-95b0d2921c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1228&q=80",
    price: "2799",
    discounted_price: "1119",
    category_name: "Candy Shop",
    category: "ESP",
    availability: true,
    delivery_time: "5",
    rating: "1.5",
  },
];
